### ISSUE TITLE
The app crashes with segmentation fault

### ISSUE THREAD

**Issue by ryonakano** [dr-Styki/ScreenRec#59]
Running the app does nothing and if we try launching the app from terminal the critical error is printed and nothing happens.

```
ryonakano@LB450M:~$ flatpak run com.github.dr_styki.screenrec 
Gtk-Message: 11:19:52.279: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:19:52.280: Failed to load module "canberra-gtk-module"

(com.github.dr_styki.screenrec:2): GLib-CRITICAL **: 11:19:52.617: g_strsplit: assertion 'string != NULL' failed
```

Debugging using gdb I get the following log message:

```
(gdb) run
Starting program: /app/bin/com.github.dr_styki.screenrec 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff28bc700 (LWP 13)]
[New Thread 0x7ffff20bb700 (LWP 14)]
Gtk-Message: 11:20:07.388: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:20:07.389: Failed to load module "canberra-gtk-module"
[Detaching after fork from child process 15]

(com.github.dr_styki.screenrec:9): GLib-CRITICAL **: 11:20:07.466: g_strsplit: assertion 'string != NULL' failed

Thread 1 "com.github.dr_s" received signal SIGSEGV, Segmentation fault.
0x00007ffff5df0edd in _cogl_check_extension () from /usr/lib/x86_64-linux-gnu/libcogl.so.20
(gdb) bt
#0  0x00007ffff5df0edd in _cogl_check_extension () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#1  0x00007ffff5df8d1c in _cogl_feature_check () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#2  0x00007ffff5e3b04a in _cogl_winsys_renderer_connect () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#3  0x00007ffff5defd00 in cogl_renderer_connect () at /usr/lib/x86_64-linux-gnu/libcogl.so.20
#4  0x00007ffff6bd3f42 in clutter_backend_real_create_context () at /usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0
#5  0x00007ffff6bee073 in _clutter_feature_init () at /usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0
#6  0x00007ffff6bff34a in clutter_init_real () at /usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0
#7  0x00007ffff6bff5b8 in post_parse_hook () at /usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0
#8  0x00007ffff7ee3d87 in g_option_context_parse () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff6c0052b in clutter_init () at /usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0
#10 0x000055555555ea49 in main ()
```

I'm using the Early Access version of elementary OS 7 based on Ubuntu 22.04 LTS and the latest version of ScreenRec (3.1.0) installed from AppCenter.

**Comment by ghost** [comment]
I'm having the exact same issue on 6.1 Jólnir, Is there any known workaround or fix?
